//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_Code_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscretionaryRule
    {
        public int DiscretionaryRuleID { get; set; }
        public int ConsultantID { get; set; }
        public int CustomerID { get; set; }
        public string Rules { get; set; }
        public Nullable<bool> CustomerBuy { get; set; }
        public Nullable<bool> CustomerSell { get; set; }
        public Nullable<bool> ConsultantBuy { get; set; }
        public Nullable<bool> ConsultantSell { get; set; }
    }
}
